# Basic Krill Configuration with Native Datatrove
# This configuration uses the native datatrove preprocessing pipeline

sequence_len: 2048
vocab_size: 32000
hub_tokenizer_id: "microsoft/DialoGPT-medium"
dataset_prepared_path: "./prepared_data"
dataset_prepared_min_length: 150

# Datatrove preprocessing configuration
deduplication_algorithm: minhash
min_length: 100
max_length: 100000
use_trafilatura: false
collect_stats: true
cleanup_temp: true
streaming: true
num_workers: 4
minhash_threshold: 0.8

# Your datasets to preprocess
datasets:
  - path: "wikitext"
    split: "train"
    text_column: "text"

hub_model_id: "your-model-id"
output_dir: "./output"
num_epochs: 1
learning_rate: 3e-4
weight_decay: 0.01
optimizer: "muon"
muon_implementation: "moonlight"
model_config_name: "small"
gradient_accumulation_steps: 1
micro_batch_size: 1