sequence_len: 8192
hub_tokenizer_id: minpeter/tiny-ko-tokenizer-32k-250725

dataset_prepared_path: ./artifacts/webtext-8k
dataset_prepared_min_length: 150

datasets:
  - path: HAERAE-HUB/KOREAN-WEBTEXT
    split: train[:10000]
    text_column: text

hub_model_id: minpeter/webtext-8k-small-250801
output_dir: ./artifacts/models/webtext-8k-small-250801

num_epochs: 10
learning_rate: 1e-3
weight_decay: 0.1
optimizer: muon

model_config_name: small