datasets:
  - path: HAERAE-HUB/KOREAN-WEBTEXT
    split: train[:10000]
    text_column: text
  - path: HAERAE-HUB/KOREAN-SyntheticText-1.5B
    split: train[:10000]
    text_column: text
  - path: minpeter/fineweb-2-edu-korean
    split: train[:10000]
    text_column: text
  - path: heegyu/korean-petitions
    split: train
    text_column: content

tokenizer:
  hub_id: minpeter/tiny-ko-tokenizer-32k-250725
  vocab_size: 32000

preprocess:
  prepared_path: ./artifacts/tiny-ko-small-250802
  sequence_len: 8192
  min_length: 150

train:
  arch: llama
  model_config_name: small
  hub_model_id: minpeter/tiny-ko-small-250802
  output_dir: ./artifacts/models/tiny-ko-small-250802
  num_epochs: 1
  learning_rate: 1e-3
  weight_decay: 0.01
  optimizer: muon
  muon_implementation: moonlight
  micro_batch_size: 16
  gradient_accumulation_steps: 1
